enum itemFlag {
	ITEM_MELEE,
	ITEM_RANGED,
	ITEM_SHIELD,
	ITEM_AMMUNITION,
	ITEM_POTION,
	ITEM_FOOD,
	ITEM_DRINK,
	ITEM_PLANT,
	ITEM_RING,
	ITEM_AMULET,
	ITEM_BELT,
	ITEM_ARMOR,
	ITEM_HELMET,
	ITEM_SCROLL,
	ITEM_RUNE,
	ITEM_NOTES,
	ITEM_BOOKS,
	ITEM_TROPHY,
	ITEM_MISC
}

enum subFlag {
	WEAPON_1HBLADE,
	WEAPON_2HBLADE,
	WEAPON_1HAXE,
	WEAPON_2HAXE
	WEAPON_1HBLUNT,
	WEAPON_2HBLUNT,
	WEAPON_DUALBLADE,
	WEAPON_STAFF,
	WEAPON_BOW,
	WEAPON_CBOW,
	POTION_PERM,
	POTION_TEMP,
	POTION_RESTORE,
	ARMOR_LEGENDARY,
	ARMOR_HIGHROBE,
	ARMOR_MIDROBE,
	ARMOR_LIGHTROBE,
	ARMOR_HEAVY,
	ARMOR_MID,
	ARMOR_LIGHT,
	ARMOR_BASIC,
	ARMOR_CLOTHING,
	ITEM_CONSUMABLE,
	ITEM_RECIPY,
	ITEM_TOOL,
	ITEM_CRAFTING,
	ITEM_LOOT,
	ITEM_KEY,
	ITEM_MISC
}

enum statRestore {
	RESTORE_HEALTH,
	RESTORE_MANA,
	RESTORE_STAMINA
}

enum inventorySlot {
	SLOT_HELMET,
	SLOT_AMULET,
	SLOT_ARMOR,
	SLOT_BELT,
	SLOT_RING,
	SLOT_SHIELD,
	SLOT_WEAPONMELEE,
	SLOT_WEAPONRANGED,
	SLOT_RUNE,
	SLOT_SCROLL,
	SLOT_HAND,
	SLOT_AMMUNITION
}

const NAME_PROT_EDGE = "Edge Protection";
const NAME_PROT_BLUNT = "Blunt Protection";
const NAME_PROT_POINT = "Point Protection";
const NAME_PROT_MAGIC = "Magic Protection";

const NAME_DAMAGE_EDGE = "Edge Damage";
const NAME_DAMAGE_BLUNT = "Blunt Damage";
const NAME_DAMAGE_POINT = "Point Damage";
const NAME_DAMAGE_MAGIC = "Magic Damage";

const NAME_CONDITION_STR = "Required Strength";
const NAME_CONDITION_DEX = "Required Dexterity";
const NAME_CONDITION_MANA = "Required Mana";

const NAME_RECOVER_HEALTH = "Recover Health";
const NAME_RECOVER_MANA = "Recover Mana";

const NAME_CHANGE_HEALTH = "Bonus Health";
const NAME_CHANGE_MANA = "Bonus Mana";
const NAME_CHANGE_STR = "Bonus Strength";
const NAME_CHANGE_DEX = "Bonus Dexterity";